### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by Kingjosh007** [android-js/androidjs#28]
I tried `androidjs b -f`, but I got this error...
stderr: provided apk path or file '...path-to-project\dist\app.apk' does not exist

**Comment by Chhekur** [comment]
May be there are some issues in`androidjs-builder@1.0.7`.
We'll fix this issues ASAP,
For now you can downgrade to older version 1.0.6 follow these steps:

```sh
npm uninstall -g androidjs-builder
npm install -g androidjs-builder@1.0.6
```
Please report us if you find any other error or bug : )

**Comment by Kingjosh007** [comment]
Thanks you. Downgrading...

**Comment by rickhall** [comment]
I see the same issue. Downgrading did allow me to continue.

**Comment by Chhekur** [comment]
> I see the same issue. Downgrading did allow me to continue.

Yeah I think there are few bugs in 1.0.7 😅, we'll fix it ASAP.
We are making `Android JS` to compatible with `react-native` and `flutter` as well to provide `Node JS` runtime environment in react native and flutter stay tuned for updates.

And when you done with your app, you build with Android JS, you can make a pull request on app-showcase to add your app on Androud JS homepage :)

**Comment by gmastergreatee** [comment]
Downgrading androidjs-builder didn't work for me
This is the error I'm getting after downgrading

![image](https://user-images.githubusercontent.com/17880848/58788681-00a32e80-860a-11e9-9f36-9e799ed390c2.png)

And this is what I get when I use the latest version

![image](https://user-images.githubusercontent.com/17880848/58788824-57106d00-860a-11e9-96d4-b73a12f5c3ff.png)

**Comment by gmastergreatee** [comment]
I'm getting error when I build a project which I created using the command
`android g`

The error is that after installing, when I launch the app, it starts but after staying for 2-3 seconds, the app closes itself(I could still see it on the task-manager). But the same problem keeps repeating whenever I try to open it/bring it to foreground from task-manager.

But if I build any of the projects which are in the [examples](https://github.com/android-js/sample-app), all of them just work fine

**Comment by Chhekur** [comment]
This is problem just because may be all the dependencies are not installed

Run  `npm install` command to install dependencies into the project folder

**Comment by gmastergreatee** [comment]
If the dependencies are missing, then the apk shouldn't even build(I think).

Nvm, previously I was using yarn for fetching the modules. Will check with npm & then report.

**Comment by Chhekur** [comment]
When the application crashes, there is always be a run time exception that can't be checked at compile time.
App crash always happend because of  mostly `node js` code so it always better to check all the required `modules` you have in `node_modules` and code you have return is correct.

And if you like the project could you please share it to make it more rechable to the community 😉

**Comment by gmastergreatee** [comment]
__NOTE :__ Only for the case of __androidjs-builder__ version __1.0.6__

Ok, I caught the error.

When I use the command 
`androidjs g`
All example files are generated except `main.js`

I included this file(which I left empty) & now everything worked like a charm

**Comment by EnterTheNameHere** [comment]
Have the same issue, downgrading works.

I've noticed:

`{ DEBUG: false,
  BUILDER__cwd: 'C:\\Users\\Jan\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder',
  PROJECT__cwd: 'D:\\Developers\\Repositories\\playfrommidi',
  PROJECT__dist: 'D:\\Developers\\Repositories\\playfrommidi\\dist',
  PROJECT__DIST__name: 'dist',
  platform: 'win32',
  force_replace: false }
skipped to copy core module !
Core Modules Copied !
copying user app done.
User data copied
reading  D:\Developers\Repositories\playfrommidi\dist\app-debug\AndroidManifest.xml
User assets cleared
package name com.androidjs.mypkg
{ '$': { 'android:name': 'android.permission.INTERNET' } }
android.webkit.PermissionRequest
Done!
AndroidManifest updated!
changing app name D:\Developers\Repositories\playfrommidi\dist\app-debug\res\values\strings.xml
{ _: 'myapp', '$': { name: 'app_name' } }
App Name updated!
Icon updated!
Building...
(node:4672) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
I: Using Apktool 2.4.0

I: Checking whether sources has changed...

I: Checking whether resources has changed...

I: Building resources...

build process exited with code 1
Build finished!
Sign apk
stderr: provided apk path or file 'D:\Developers\Repositories\playfrommidi\dist\app.apk' does not exist
stderr: 

stderr: java.lang.IllegalArgumentException: provided apk path or file 'D:\Developers\Repositories\playfrommidi\dist\app.apk' does not exist
stderr: 

stderr: 	at at.favre.tools.apksigner.ui.FileArgParser.parseAndSortUniqueFilesNonRecursive(FileArgParser.java:38)

stderr: 	at at.favre.tools.apksigner.SignTool.execute(SignTool.java:63)
	at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:48)
	at at.favre.tools.apksigner.SignTool.main(SignTool.java:36)

stderr: 
Cmd history for debugging purpose:
-----------------------


sign process exited with code 1
`

The line 'build process exited with code 1'
I assume that means some error occured during the build process, however no info about the error is given.

**Comment by danbulant** [comment]
1.0.9 still the same error, looks like the build proces fails, but no error given

**Comment by Chhekur** [comment]
> 1.0.9 still the same error, looks like the build proces fails, but no error given

We didn't released 1.0.9 yet, How did you get that ?

**Comment by hacp0012** [comment]
Plz help me when i want to build , i get this error msg :

/

```
> usr/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
>     if ('number' != typeof options.total) throw new Error('total required');
>                                           ^
> 
> Error: total required
```

**Comment by Chhekur** [comment]
> Plz help me when i want to build , i get this error msg :
> 
> /
> 
> ```
> > usr/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
> >     if ('number' != typeof options.total) throw new Error('total required');
> >                                           ^
> > 
> > Error: total required
> ```

Run the build command and make sure you are connected to internet, this occurs sometimes when your internet connection and get the payload with size 0 ; P

**Comment by Chhekur** [comment]
> Having the issue when i wnat to build the package:
> Not a androidjs project
> 
> I am using version 2.0.2

Define `project_type` attribute in `Package.json`
Check out the [docs](https://android-js.github.io/docs/configuring_app.html#define-project-type)

**Comment by SOFTWORLDIT** [comment]
C:\Users\USER\desktop\myapp> androidjs b -f
webview: androidjs
building
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
 downloading sdk [ ======================================== ] 54041796/54345243 734553/bps 99% 0.4s done
extracting: https://github.com/android-js/androidjs-sdk to: C:\Users\USER\.androidjs\androidjs-sdk
 ✔ done
copying Assets
copying from C:\Users\USER\desktop\myapp
to: C:\Users\USER\.androidjs\androidjs-sdk\assets\myapp
[ 'C:\\Users\\USER\\desktop\\myapp\\dist' ]

But I could not find dist directory in my "myapp"

**Comment by SOFTWORLDIT** [comment]
On rebuild: I had this

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\USER\desktop\myapp\ '
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
PS C:\Users\USER\desktop\myapp>

**Comment by Chhekur** [comment]
> On rebuild: I had this
> 
> events.js:174
> throw er; // Unhandled 'error' event
> ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\USER\desktop\myapp\ '
> Emitted 'error' event at:
> at lazyFs.open (internal/fs/streams.js:115:12)
> at FSReqWrap.args [as oncomplete] (fs.js:140:20)
> PS C:\Users\USER\desktop\myapp>

Looks like you don't have folder with name `myapp` on desktop
Please check that out first.

**Comment by SOFTWORLDIT** [comment]
My good brother, I have it sir.

**Comment by Chhekur** [comment]
> My good brother, I have it sir.

Try to rebuild again and provide me full log.

**Comment by SOFTWORLDIT** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/55089050/64529539-0a23ed00-d303-11e9-9f4a-a74abced5662.png)

**Comment by SOFTWORLDIT** [comment]
C:\Users\USER\desktop\myapp> androidjs b -f
webview: androidjs
building
checking Core
using core C:\Users\USER\.androidjs\androidjs-sdk
removing C:\Users\USER\.androidjs\androidjs-sdk\assets\myapp/*
copying Assets
copying from C:\Users\USER\desktop\myapp
to: C:\Users\USER\.androidjs\androidjs-sdk\assets\myapp
[ 'C:\\Users\\USER\\desktop\\myapp\\dist' ]
changing icon
icons Updated
changing configuration
reading  C:\Users\USER\.androidjs\androidjs-sdk\AndroidManifest.xml
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\USER\desktop\myapp\ '
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
PS C:\Users\USER\desktop\myapp>

**Comment by Chhekur** [comment]
> C:\Users\USER\desktop\myapp> androidjs b -f
> webview: androidjs
> building
> checking Core
> using core C:\Users\USER.androidjs\androidjs-sdk
> removing C:\Users\USER.androidjs\androidjs-sdk\assets\myapp/*
> copying Assets
> copying from C:\Users\USER\desktop\myapp
> to: C:\Users\USER.androidjs\androidjs-sdk\assets\myapp
> [ 'C:\Users\USER\desktop\myapp\dist' ]
> changing icon
> icons Updated
> changing configuration
> reading C:\Users\USER.androidjs\androidjs-sdk\AndroidManifest.xml
> events.js:174
> throw er; // Unhandled 'error' event
> ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\USER\desktop\myapp\ '
> Emitted 'error' event at:
> at lazyFs.open (internal/fs/streams.js:115:12)
> at FSReqWrap.args [as oncomplete] (fs.js:140:20)
> PS C:\Users\USER\desktop\myapp>

Can you provide your package.json file

**Comment by SOFTWORLDIT** [comment]
{
  "name": "androidjs",
  "version": "2.0.1",
  "description": "SOFTWORLD APPS",
  "main": "index.js",
  "project-type":"webview",
  "icon":" ",
  "app-name":"myapp ",
  "package-name":"package.json",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "node ./src/build.js"
  },
  "author": "Harendra Chhekur <820121223505e@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "@types/dom-mediacapture-record": "^1.0.1",
    "@types/node": "^11.13.9",
    "Buffer": "0.0.0",
    "react-native": "^0.59.9",
    "socket.io": "^2.2.0",
    "socket.io-client": "^2.2.0",
    "ts-loader": "^5.4.5",
    "typescript": "^3.4.5",
    "webpack": "^4.30.0",
    "webpack-node-externals": "^1.7.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/android-js/androidjs"
  },
  "homepage": "https://android-js.github.io"
}

**Comment by SOFTWORLDIT** [comment]
I follow everything in your study class. I got to your page yesterday. I knew nothing about androidjs before until I met you

**Comment by Chhekur** [comment]
> {
> "name": "androidjs",
> "version": "2.0.1",
> "description": "SOFTWORLD APPS",
> "main": "index.js",
> "project-type":"webview",
> "icon":" ",
> "app-name":"myapp ",
> "package-name":"package.json",
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1",
> "build": "node ./src/build.js"
> },
> "author": "Harendra Chhekur [820121223505e@gmail.com](mailto:820121223505e@gmail.com)",
> "license": "MIT",
> "dependencies": {
> "@types/dom-mediacapture-record": "^1.0.1",
> "@types/node": "^11.13.9",
> "Buffer": "0.0.0",
> "react-native": "^0.59.9",
> "socket.io": "^2.2.0",
> "socket.io-client": "^2.2.0",
> "ts-loader": "^5.4.5",
> "typescript": "^3.4.5",
> "webpack": "^4.30.0",
> "webpack-node-externals": "^1.7.2"
> },
> "repository": {
> "type": "git",
> "url": "https://github.com/android-js/androidjs"
> },
> "homepage": "https://android-js.github.io"
> }

There are lot's of mistakes in your `package.json` file that's why error occurs
Check out the documentation to fix all the configurations [click here](https://android-js.github.io/docs/configuring_app.html)

**Comment by SOFTWORLDIT** [comment]
My brother, should I just copy and paste from this:
This is one of the scripts I found in the link. Do I need to edit the name,app-name and version?
{
  "name": "myfirstapp",
  "app-name" : "My First App",
  "package-name": "myapp",
  "permission": ["android.permission.INTERNET", "android.permission.SEND_SMS"],
  "dist-path": "./dist",
  "project-type":"webview",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

**Comment by Chhekur** [comment]
> My brother, should I just copy and paste from this:
> This is one of the scripts I found in the link. Do I need to edit the name,app-name and version?
> {
> "name": "myfirstapp",
> "app-name" : "My First App",
> "package-name": "myapp",
> "permission": ["android.permission.INTERNET", "android.permission.SEND_SMS"],
> "dist-path": "./dist",
> "project-type":"webview",
> "version": "1.0.0",
> "description": "",
> "main": "index.js",
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1"
> },
> "author": "",
> "license": "ISC"
> }

Yes, you can.
but make sure all the configurations are correct because there are 4 to 5 different sections of configuration and one more thing all the configurations are mandatory!

**Comment by SOFTWORLDIT** [comment]
I corrected the package.json to:
{
  "name": "myfirstapp",
  "app-name" : "MyFirstApp",
  "package-name": "myapp",
  "icon":"./assets/icon/network.png",
  "permission": ["android.permission.INTERNET", "android.permission.SEND_SMS"],
  "dist-path": "./dist",
  "project-type":"webview",
  "version": "2.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Abu",
  "license": "ISC"
}

AFTER REBUILD RESULT IS:

C:\Users\USER\desktop\myapp> androidjs b -f
webview: myfirstapp
building
checking Core
using core C:\Users\USER\.androidjs\androidjs-sdk
removing C:\Users\USER\.androidjs\androidjs-sdk\assets\myapp/*
copying Assets
copying from C:\Users\USER\desktop\myapp
to: C:\Users\USER\.androidjs\androidjs-sdk\assets\myapp
[ 'C:\\Users\\USER\\desktop\\myapp\\dist' ]
changing icon
icons Updated
changing configuration
reading  C:\Users\USER\.androidjs\androidjs-sdk\AndroidManifest.xml
{ manifest:
   { '$':
      { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
        package: 'com.android.js.webview',
        platformBuildVersionCode: '28',
        platformBuildVersionName: '9' },
     'uses-permission':
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     application: [ [Object] ] } }
package name com.android.js.myapp
{ '$': { 'android:name': 'android.permission.INTERNET' } }
{ '$': { 'android:name': 'android.permission.SEND_SMS' } }
Done!
Updating C:\Users\USER\.androidjs\androidjs-sdk\res\values\strings.xml
{ _: 'MyFirstApp', '$': { name: 'app_name' } }
Building APK
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Chhekur** [comment]
> I corrected the package.json to:
> {
> "name": "myfirstapp",
> "app-name" : "MyFirstApp",
> "package-name": "myapp",
> "icon":"./assets/icon/network.png",
> "permission": ["android.permission.INTERNET", "android.permission.SEND_SMS"],
> "dist-path": "./dist",
> "project-type":"webview",
> "version": "2.0.1",
> "description": "",
> "main": "index.js",
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1"
> },
> "author": "Abu",
> "license": "ISC"
> }
> 
> AFTER REBUILD RESULT IS:
> 
> C:\Users\USER\desktop\myapp> androidjs b -f
> webview: myfirstapp
> building
> checking Core
> using core C:\Users\USER.androidjs\androidjs-sdk
> removing C:\Users\USER.androidjs\androidjs-sdk\assets\myapp/*
> copying Assets
> copying from C:\Users\USER\desktop\myapp
> to: C:\Users\USER.androidjs\androidjs-sdk\assets\myapp
> [ 'C:\Users\USER\desktop\myapp\dist' ]
> changing icon
> icons Updated
> changing configuration
> reading C:\Users\USER.androidjs\androidjs-sdk\AndroidManifest.xml
> { manifest:
> { '$':
> { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
> package: 'com.android.js.webview',
> platformBuildVersionCode: '28',
> platformBuildVersionName: '9' },
> 'uses-permission':
> [ [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object],
> [Object] ],
> application: [ [Object] ] } }
> package name com.android.js.myapp
> { '$': { 'android:name': 'android.permission.INTERNET' } }
> { '$': { 'android:name': 'android.permission.SEND_SMS' } }
> Done!
> Updating C:\Users\USER.androidjs\androidjs-sdk\res\values\strings.xml
> { _: 'MyFirstApp', '$': { name: 'app_name' } }
> Building APK
> events.js:174
> throw er; // Unhandled 'error' event
> ^
> 
> Error: spawn java ENOENT
> at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> at onErrorNT (internal/child_process.js:415:16)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> Emitted 'error' event at:
> at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
> at onErrorNT (internal/child_process.js:415:16)
> at process._tickCallback (internal/process/next_tick.js:63:19)

Kindly generate the project using `CLI tool`, it will automatically create a sample app with all configuration for you!

**Comment by SOFTWORLDIT** [comment]
Heeeeeee! brother! which one is CLI tool?

**Comment by Chhekur** [comment]
> Heeeeeee! brother! which one is CLI tool?

`androidjs-builder` check out the documentation (click here)[https://npmjs.com/packages/androidjs-builder]

**Comment by RayanLA** [comment]
Having the same issue _stderr: provided apk path or file '...path-to-project\dist\app.apk' does not exist_ 
but even for version androidjs 1.0.6 ... 
please help o_O

**Comment by auxmall** [comment]
I am getting this problem can you help me

root@kali:~/Downloads/sample-app-master/music app# androidjs b -f
copying user app done.
User data copied
app core copied !
Core Modules Copied !
reading  /root/Downloads/sample-app-master/music app/dist/app-debug/AndroidManifest.xml
package name com.androidjs.music
{ '$': { 'android:name': 'android.permission.INTERNET' } }
{
  '$': { 'android:name': 'android.permission.WRITE_EXTERNAL_STORAGE' }
}
{ '$': { 'android:name': 'android.permission.READ_EXTERNAL_STORAGE' } }
Done!
AndroidManifest updated!
changing app name /root/Downloads/sample-app-master/music app/dist/app-debug/res/values/strings.xml
{ _: 'My Music', '$': { name: 'app_name' } }
App Name updated!
Icon updated!
Building...
(node:6983) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
I: Using Apktool 2.4.0

I: Checking whether sources has changed...

I: Smaling smali folder into classes.dex...

I: Checking whether resources has changed...

I: Building resources...

build process exited with code 1
Build finished!
Sign apk
stderr: provided apk path or file '/root/Downloads/sample-app-master/music app/dist/app.apk' does not exist

stderr: java.lang.IllegalArgumentException: provided apk path or file '/root/Downloads/sample-app-master/music app/dist/app.apk' does not exist
	at at.favre.tools.apksigner.ui.FileArgParser.parseAndSortUniqueFilesNonRecursive(FileArgParser.java:38)
	at at.favre.tools.apksigner.SignTool.execute(SignTool.java:63)
	at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:48)
	at at.favre.tools.apksigner.SignTool.main(SignTool.java:36)

stderr: 
Cmd history for debugging purpose:
-----------------------


sign process exited with code 1
